version: 0.2

phases:
  install:
    commands:
      - curl -o flutter.tar.xz https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.29.3-stable.tar.xz
      - tar xf flutter.tar.xz
      - export PATH="$PATH:`pwd`/flutter/bin"
      - git config --global --add safe.directory `pwd`/flutter
      - flutter doctor

  pre_build:
    commands:
      - export PATH="$PATH:`pwd`/flutter/bin"
      - flutter pub get

  build:
    commands:
      - export PATH="$PATH:`pwd`/flutter/bin"
      - flutter build web --release

  post_build:
    commands:
      - aws s3 sync build/web/ s3://formulario-ottokare/ --delete

artifacts:
  files:
    - '**/*'
  base-directory: build/web